### ISSUE TITLE
NPY file at the root of the workspace

### ISSUE THREAD

**Issue by RemiRigal** [AlexandreCourjaud/Hexabot#31]
Files useful for the development such as [depth.npy](https://github.com/AlexandreCourjaud/Hexabot/blob/master/workspaceRos/depth.npy) should not be at the root of the [catkin workspace](https://github.com/AlexandreCourjaud/Hexabot/blob/master/workspaceRos).

**Comment by corentin-j** [comment]
File deleted, but i don't remember when
