### ISSUE TITLE
Bad while loop in 'cave_explorer.py'

### ISSUE THREAD

**Issue by RemiRigal** [AlexandreCourjaud/Hexabot#47]
The use of `while True` without any breaks must be avoided.
For ROS, a good practice is to use `not rospy.is_shutdown()` for the loop condition. See this [link](http://wiki.ros.org/rospy/Overview/Initialization%20and%20Shutdown) for more details.

https://github.com/AlexandreCourjaud/Hexabot/blob/e6e28fe1e5e4c09569a5e8c8cfc2624c17a0557f/workspaceRos/src/phantomx/phantomx_control/src/cave_explorer.py#L89

**Comment by Bulowl** [comment]
Changed `while true` to `not rospy.is_shutdown()`

**Comment by AlexandreCourjaud** [comment]
#54
