### ISSUE TITLE
Useless 'pass' in 'cave_explorer.py'

### ISSUE THREAD

**Issue by RemiRigal** [AlexandreCourjaud/Hexabot#48]
https://github.com/AlexandreCourjaud/Hexabot/blob/e6e28fe1e5e4c09569a5e8c8cfc2624c17a0557f/workspaceRos/src/phantomx/phantomx_control/src/cave_explorer.py#L106

**Comment by Bulowl** [comment]
Remnant of a past iteration of the code, removed

**Comment by AlexandreCourjaud** [comment]
#54
