### ISSUE TITLE
Use of 'print' for logging

### ISSUE THREAD

**Issue by RemiRigal** [AlexandreCourjaud/Hexabot#49]
The python `print` must never be used in a ROS node.

https://github.com/AlexandreCourjaud/Hexabot/blob/e6e28fe1e5e4c09569a5e8c8cfc2624c17a0557f/workspaceRos/src/phantomx/phantomx_gazebo/scripts/walker_demo.py#L17

**Comment by Bulowl** [comment]
`print` were used for debugging, changed to commented status

**Comment by AlexandreCourjaud** [comment]
#54
