### ISSUE TITLE
Several issues in sort_fissures.py

### ISSUE THREAD

**Issue by TilletJ** [AlexandreCourjaud/Hexabot#66]
- L13: import time is not used and should not be used in the context of simulations
- Use of prints
- In the `main` part, you declare a subscriber before initiating the node.

https://github.com/AlexandreCourjaud/Hexabot/blob/17d00894e3ecddf84d443a432f6e400d23d4998e/workspaceRos/src/phantomx/phantomx_camera/src/sort_fissures.py

**Comment by corentin-j** [comment]
Currently working on this script, this issue will be solved this afternoon.

**Comment by TilletJ** [comment]
So why this script is on the master branch ? 🤔

**Comment by ymusell** [comment]
Done #69
